# http://about.travis-ci.org/docs/user/languages/python/

language: python
python:
  - "2.6"
  - "2.7"

install: 
  - pip install -r requirements.txt --use-mirrors
  #- python setup.py install

before_script:
  - pip install -r requirements_test.txt --use-mirrors

script: 
  - py.test --pep8 -v